Write-Host "GeekIT Mapping drive using powershell"
New-PSDrive -Name "test" -PSProvider "FileSystem" -Root "\\appserver\Public"
Write-Host "Drive is created"
Write-Host "create a temporary drive"
New-PSDrive -Name "Test" -PSProvider Environment -Root "C:\Users\.........\Documents" -Description "Test"
Write-Host "Temporary drive created"
Write-Host "Drive for the registry key"
New-PSDrive -Name "test" -PSProvider "Registry" -Root "HKLM:\Software\test"
Write-Host "Registry drive created"