# Module manifest for module 'MyGetBIOS'
#
# Generated by: Vasilis Psaromatis
#
# Generated on: 2022!
#
 
@{
 
# Script module or binary module file associated with this manifest
ModuleToProcess = 'GetBIOS.psm1'
 
# Version number of this module.
ModuleVersion = '1.3.1'
 
# ID used to uniquely identify this module
GUID = 'dfead4da-a96b-4fb7-abb9-e73702e88eb2'
 
# Author of this module
Author = 'Vasilis PS'
 
# Company or vendor of this module
CompanyName = 'Vasilis PS PCTECHGREU'
 
# Copyright statement for this module
Copyright = '(c) 2022 Vasilis PS. All rights reserved.'
 
# Description of the functionality provided by this module
Description = 'List local or remote BIOS settings (for Lenovo, Dell, HP and Toshiba)'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''
 
# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''
 
# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''
 
# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''
 
# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''
 
# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''
 
# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()
 
# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()
 
# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()
 
# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()
 
# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()
 
# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = @()
 
# Functions to export from this module
FunctionsToExport = '*'
 
# Cmdlets to export from this module
CmdletsToExport = '*'
 
# Variables to export from this module
VariablesToExport = '*'
 
# Aliases to export from this module
AliasesToExport = '*'
 
# List of all modules packaged with this module
ModuleList = @()
 
# List of all files packaged with this module
FileList = 'GetBIOS.psm1'

# Private data to pass to the module specified in ModuleToProcess
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
         Tags = @('BIOS','BIOS-settings','HP', 'Lenovo', 'Dell )

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo of this module
# HelpInfo = ' TELEPHONE 6981550298'

}

